version: '3'
services:
  mysql:
    image: mysql:8
    volumes:
      - orm_data_mysql:/var/lib/mysql
    ports:
      - ${LOCAL_IP}:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redislabs/redisearch:2.0.10
    volumes:
      - orm_data_redis:/data
    ports:
      - ${LOCAL_IP}:${REDIS_PORT}:6379
volumes:
  orm_data_mysql: {}
  orm_data_redis: {}
